
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.navi.backend.flexycup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BORRAR_PAGINA = 15;
  public static final int ALINEACION = 31;
  public static final int PAGINA = 28;
  public static final int PARAMETROS = 5;
  public static final int SLASH = 37;
  public static final int NOMBRE = 4;
  public static final int ANCHO = 35;
  public static final int ETIQUETAS = 7;
  public static final int PARAM = 41;
  public static final int TITULO = 25;
  public static final int PADRE = 27;
  public static final int ID = 20;
  public static final int NUEVA_PAGINA = 14;
  public static final int EOF = 0;
  public static final int BORRAR_COMPONENTE = 18;
  public static final int EQUAL = 40;
  public static final int CLASE = 29;
  public static final int error = 1;
  public static final int CADENA = 42;
  public static final int MENOR = 39;
  public static final int FECHA_MODIFICACION = 23;
  public static final int ETIQUETAS_NOMBRE = 36;
  public static final int ATRIBUTOS = 10;
  public static final int ATRIBUTO = 11;
  public static final int ACCION = 3;
  public static final int COLOR = 32;
  public static final int MAYOR = 38;
  public static final int USUARIO_MODIFICACION = 24;
  public static final int FECHA_CREACION = 22;
  public static final int NUEVO_SITIO_WEB = 12;
  public static final int USUARIO_CREACION = 21;
  public static final int VALOR = 9;
  public static final int MODIFICAR_COMPONENTE = 19;
  public static final int ORIGEN = 33;
  public static final int AGREGAR_COMPONENTE = 17;
  public static final int PARAMETRO = 6;
  public static final int ACCIONES = 2;
  public static final int SITIO = 26;
  public static final int TEXTO = 30;
  public static final int ETIQUETA = 8;
  public static final int ALTURA = 34;
  public static final int BORRRAR_SITIO_WEB = 13;
  public static final int MODIFICAR_PAGINA = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ACCIONES",
  "ACCION",
  "NOMBRE",
  "PARAMETROS",
  "PARAMETRO",
  "ETIQUETAS",
  "ETIQUETA",
  "VALOR",
  "ATRIBUTOS",
  "ATRIBUTO",
  "NUEVO_SITIO_WEB",
  "BORRRAR_SITIO_WEB",
  "NUEVA_PAGINA",
  "BORRAR_PAGINA",
  "MODIFICAR_PAGINA",
  "AGREGAR_COMPONENTE",
  "BORRAR_COMPONENTE",
  "MODIFICAR_COMPONENTE",
  "ID",
  "USUARIO_CREACION",
  "FECHA_CREACION",
  "FECHA_MODIFICACION",
  "USUARIO_MODIFICACION",
  "TITULO",
  "SITIO",
  "PADRE",
  "PAGINA",
  "CLASE",
  "TEXTO",
  "ALINEACION",
  "COLOR",
  "ORIGEN",
  "ALTURA",
  "ANCHO",
  "ETIQUETAS_NOMBRE",
  "SLASH",
  "MAYOR",
  "MENOR",
  "EQUAL",
  "PARAM",
  "CADENA"
  };
}

