
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.navi.backend.flexycup;

import java_cup.runtime.*;
import com.navi.backend.webController.*;
import javax.swing.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class XMLParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public XMLParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public XMLParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public XMLParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\066\000\002\002\004\000\002\002\003\000\002\002" +
    "\003\000\002\003\012\000\002\003\007\000\002\004\004" +
    "\000\002\004\003\000\002\005\007\000\002\005\007\000" +
    "\002\005\007\000\002\005\007\000\002\005\007\000\002" +
    "\005\007\000\002\005\007\000\002\005\007\000\002\006" +
    "\006\000\002\007\006\000\002\021\003\000\002\015\004" +
    "\000\002\015\004\000\002\014\004\000\002\014\004\000" +
    "\002\017\012\000\002\020\003\000\002\020\004\000\002" +
    "\016\007\000\002\016\007\000\002\016\007\000\002\016" +
    "\007\000\002\016\007\000\002\016\007\000\002\016\007" +
    "\000\002\016\007\000\002\016\007\000\002\016\007\000" +
    "\002\010\006\000\002\011\006\000\002\023\012\000\002" +
    "\024\003\000\002\024\004\000\002\022\011\000\002\026" +
    "\012\000\002\027\003\000\002\027\004\000\002\025\007" +
    "\000\002\025\007\000\002\025\007\000\002\025\007\000" +
    "\002\025\007\000\002\025\007\000\002\025\007\000\002" +
    "\025\007\000\002\012\006\000\002\013\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\307\000\006\003\006\051\007\001\002\000\004\002" +
    "\uffff\001\002\000\004\002\000\001\002\000\004\051\275" +
    "\001\002\000\006\004\272\005\271\001\002\000\004\002" +
    "\270\001\002\000\022\016\017\017\015\020\016\021\021" +
    "\022\012\023\020\024\013\025\014\001\002\000\004\050" +
    "\265\001\002\000\004\050\262\001\002\000\004\050\257" +
    "\001\002\000\004\050\254\001\002\000\004\050\223\001" +
    "\002\000\004\050\220\001\002\000\004\050\125\001\002" +
    "\000\004\050\022\001\002\000\004\051\024\001\002\000" +
    "\004\051\ufff0\001\002\000\004\007\033\001\002\000\004" +
    "\051\026\001\002\000\004\047\030\001\002\000\006\002" +
    "\ufff7\051\ufff7\001\002\000\004\005\031\001\002\000\004" +
    "\050\032\001\002\000\006\002\ufff1\051\ufff1\001\002\000" +
    "\004\050\034\001\002\000\004\051\037\001\002\000\004" +
    "\051\120\001\002\000\026\026\053\027\044\030\054\031" +
    "\051\032\055\033\046\034\045\035\047\036\050\037\052" +
    "\001\002\000\004\010\041\001\002\000\004\051\uffea\001" +
    "\002\000\004\006\042\001\002\000\004\052\043\001\002" +
    "\000\026\026\uffde\027\uffde\030\uffde\031\uffde\032\uffde\033" +
    "\uffde\034\uffde\035\uffde\036\uffde\037\uffde\001\002\000\004" +
    "\050\115\001\002\000\004\050\112\001\002\000\004\050" +
    "\107\001\002\000\004\050\104\001\002\000\004\050\101" +
    "\001\002\000\004\050\076\001\002\000\004\050\073\001" +
    "\002\000\004\050\070\001\002\000\004\050\065\001\002" +
    "\000\004\050\056\001\002\000\004\053\057\001\002\000" +
    "\004\051\060\001\002\000\004\047\062\001\002\000\004" +
    "\051\uffe4\001\002\000\004\010\063\001\002\000\004\050" +
    "\064\001\002\000\004\051\uffdd\001\002\000\004\053\066" +
    "\001\002\000\004\051\060\001\002\000\004\051\uffe6\001" +
    "\002\000\004\053\071\001\002\000\004\051\060\001\002" +
    "\000\004\051\uffe8\001\002\000\004\053\074\001\002\000" +
    "\004\051\060\001\002\000\004\051\uffdf\001\002\000\004" +
    "\053\077\001\002\000\004\051\060\001\002\000\004\051" +
    "\uffe5\001\002\000\004\053\102\001\002\000\004\051\060" +
    "\001\002\000\004\051\uffe0\001\002\000\004\053\105\001" +
    "\002\000\004\051\060\001\002\000\004\051\uffe1\001\002" +
    "\000\004\053\110\001\002\000\004\051\060\001\002\000" +
    "\004\051\uffe3\001\002\000\004\053\113\001\002\000\004" +
    "\051\060\001\002\000\004\051\uffe2\001\002\000\004\053" +
    "\116\001\002\000\004\051\060\001\002\000\004\051\uffe7" +
    "\001\002\000\006\010\041\047\122\001\002\000\004\051" +
    "\uffe9\001\002\000\004\007\123\001\002\000\004\050\124" +
    "\001\002\000\004\051\uffeb\001\002\000\004\051\131\001" +
    "\002\000\004\051\024\001\002\000\004\051\026\001\002" +
    "\000\004\051\215\001\002\000\006\007\033\014\132\001" +
    "\002\000\004\050\133\001\002\000\004\051\136\001\002" +
    "\000\004\051\uffd7\001\002\000\004\051\210\001\002\000" +
    "\004\015\204\001\002\000\022\035\146\040\140\041\142" +
    "\042\141\043\143\044\144\045\145\046\147\001\002\000" +
    "\004\050\201\001\002\000\004\050\176\001\002\000\004" +
    "\050\173\001\002\000\004\050\170\001\002\000\004\050" +
    "\165\001\002\000\004\050\162\001\002\000\004\050\157" +
    "\001\002\000\004\050\150\001\002\000\004\053\151\001" +
    "\002\000\004\051\153\001\002\000\004\051\uffce\001\002" +
    "\000\004\047\154\001\002\000\004\015\155\001\002\000" +
    "\004\050\156\001\002\000\004\051\uffcc\001\002\000\004" +
    "\053\160\001\002\000\004\051\153\001\002\000\004\051" +
    "\uffcf\001\002\000\004\053\163\001\002\000\004\051\153" +
    "\001\002\000\004\051\uffd0\001\002\000\004\053\166\001" +
    "\002\000\004\051\153\001\002\000\004\051\uffd1\001\002" +
    "\000\004\053\171\001\002\000\004\051\153\001\002\000" +
    "\004\051\uffd2\001\002\000\004\053\174\001\002\000\004" +
    "\051\153\001\002\000\004\051\uffd4\001\002\000\004\053" +
    "\177\001\002\000\004\051\153\001\002\000\004\051\uffd3" +
    "\001\002\000\004\053\202\001\002\000\004\051\153\001" +
    "\002\000\004\051\uffd5\001\002\000\004\006\205\001\002" +
    "\000\004\052\206\001\002\000\022\035\uffcd\040\uffcd\041" +
    "\uffcd\042\uffcd\043\uffcd\044\uffcd\045\uffcd\046\uffcd\001\002" +
    "\000\004\051\uffd6\001\002\000\006\015\204\047\211\001" +
    "\002\000\004\014\212\001\002\000\004\050\213\001\002" +
    "\000\004\051\uffd8\001\002\000\004\051\uffed\001\002\000" +
    "\004\014\132\001\002\000\006\002\ufff5\051\ufff5\001\002" +
    "\000\004\051\uffec\001\002\000\004\051\024\001\002\000" +
    "\004\051\026\001\002\000\006\002\ufffa\051\ufffa\001\002" +
    "\000\004\051\225\001\002\000\004\051\252\001\002\000" +
    "\006\007\033\011\232\001\002\000\004\051\026\001\002" +
    "\000\004\051\024\001\002\000\004\051\uffee\001\002\000" +
    "\006\002\ufff8\051\ufff8\001\002\000\004\050\233\001\002" +
    "\000\004\051\236\001\002\000\004\051\246\001\002\000" +
    "\004\051\uffdb\001\002\000\004\012\237\001\002\000\004" +
    "\013\240\001\002\000\004\052\241\001\002\000\004\054" +
    "\242\001\002\000\004\047\243\001\002\000\004\050\244" +
    "\001\002\000\004\051\uffd9\001\002\000\004\051\uffda\001" +
    "\002\000\006\012\237\047\247\001\002\000\004\011\250" +
    "\001\002\000\004\050\251\001\002\000\004\051\uffdc\001" +
    "\002\000\004\011\232\001\002\000\004\051\uffef\001\002" +
    "\000\004\051\024\001\002\000\004\051\026\001\002\000" +
    "\006\002\ufff9\051\ufff9\001\002\000\004\051\131\001\002" +
    "\000\004\051\026\001\002\000\006\002\ufff3\051\ufff3\001" +
    "\002\000\004\051\131\001\002\000\004\051\026\001\002" +
    "\000\006\002\ufff4\051\ufff4\001\002\000\004\051\225\001" +
    "\002\000\004\051\026\001\002\000\006\002\ufff6\051\ufff6" +
    "\001\002\000\004\002\001\001\002\000\004\006\304\001" +
    "\002\000\004\050\273\001\002\000\004\051\275\001\002" +
    "\000\004\051\ufffb\001\002\000\004\005\271\001\002\000" +
    "\004\051\300\001\002\000\004\051\ufffc\001\002\000\006" +
    "\005\271\047\301\001\002\000\004\004\302\001\002\000" +
    "\004\050\303\001\002\000\004\002\ufffe\001\002\000\004" +
    "\052\305\001\002\000\022\016\ufff2\017\ufff2\020\ufff2\021" +
    "\ufff2\022\ufff2\023\ufff2\024\ufff2\025\ufff2\001\002\000\004" +
    "\051\307\001\002\000\006\004\310\005\271\001\002\000" +
    "\004\050\311\001\002\000\004\002\ufffd\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\307\000\012\002\007\003\003\005\004\006\010\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\004\305" +
    "\005\273\006\010\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\017\022\021\024\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\007\026\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\010\035\016\037\020\034" +
    "\001\001\000\006\010\035\016\120\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\011\060\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\066\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\011\071\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\011\074\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\011\077\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\011\102\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\011\105" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\110\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\011\113\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\011\116\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\014\126\017\127\026\125\001\001" +
    "\000\004\017\216\001\001\000\004\007\215\001\001\000" +
    "\004\026\213\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\012\136\025\133\027\134\001\001\000\002\001" +
    "\001\000\006\012\136\025\206\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\013\151\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\013\160\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\163\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\013\166\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\013\171\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\013\174" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\013" +
    "\177\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\013\202\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\017\022\021\220\001\001\000" +
    "\004\007\221\001\001\000\002\001\001\000\010\015\225" +
    "\017\223\023\226\001\001\000\004\023\252\001\001\000" +
    "\002\001\001\000\004\007\230\001\001\000\004\017\227" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\022\234\024\233\001\001\000\004\022\244" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\017" +
    "\022\021\254\001\001\000\004\007\255\001\001\000\002" +
    "\001\001\000\010\014\257\017\127\026\125\001\001\000" +
    "\004\007\260\001\001\000\002\001\001\000\010\014\262" +
    "\017\127\026\125\001\001\000\004\007\263\001\001\000" +
    "\002\001\001\000\010\015\265\017\223\023\226\001\001" +
    "\000\004\007\266\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\004\275" +
    "\005\273\006\010\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\005\276\006\010\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\005\276\006\010\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$XMLParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$XMLParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$XMLParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public Actions actions = new Actions();
    //public ArrayList<FileTextPane> panes = new ArrayList<>();
    public XMLParser(XMLLexer lex) {
        super(lex);
    }
    //Metodo al que se llama ante algun error sintactico
    public void syntax_error(Symbol s){
        String lexeme = s.value.toString();

        int line = s.left;
        int col = s.right;
        System.out.println("ERROR SINTÁCTICO RECUPERADO");
        System.out.println("\tLexeme: " + lexeme);
        System.out.println("\tTipo: " + s.sym);
        System.out.println("\trow: " + line);
        System.out.println("\tcol: " + col);
        TError err = new TError(lexeme,"Error Sintáctico", "Token no esperado", line, col);
        //Querys.errors.add(err);
    }

    //Metodo que se llama en el momento en que ya no es posible una recuperacion
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        String lexeme = s.value.toString();
        int line = s.left;
        int col = s.right;
        System.out.println("ERROR SINTACTICO NO RECUPERABLE");
        System.out.println("\tLexeme: " + lexeme);
        System.out.println("\trow: " + line);
        System.out.println("\tcol: " + col);
        TError err = new TError(lexeme,"Error Sintáctico", "Token no esperado", line, col);
        //Querys.errors.add(err);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$XMLParser$actions {
  private final XMLParser parser;

  /** Constructor */
  CUP$XMLParser$actions(XMLParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$XMLParser$do_action_part00000000(
    int                        CUP$XMLParser$act_num,
    java_cup.runtime.lr_parser CUP$XMLParser$parser,
    java.util.Stack            CUP$XMLParser$stack,
    int                        CUP$XMLParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$XMLParser$result;

      /* select the action based on the action number */
      switch (CUP$XMLParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= actions EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		RESULT = start_val;
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$XMLParser$parser.done_parsing();
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // actions ::= accion 
            {
              Object RESULT =null;

              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("actions",0, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // actions ::= acciones 
            {
              Object RESULT =null;

              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("actions",0, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // acciones ::= MENOR ACCIONES MAYOR accionP MENOR SLASH ACCIONES MAYOR 
            {
              Object RESULT =null;

              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("acciones",1, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-7)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // acciones ::= error accionP MENOR ACCIONES MAYOR 
            {
              Object RESULT =null;

              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("acciones",1, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // accionP ::= accionP accion 
            {
              Object RESULT =null;

              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("accionP",2, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // accionP ::= accion 
            {
              Object RESULT =null;

              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("accionP",2, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // accion ::= accion_open NUEVO_SITIO_WEB MAYOR action_bodyP accion_close 
            {
              Object RESULT =null;
		int listPleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int listPright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ArrayList<Parameter> listP = (ArrayList<Parameter>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            actions.createSite(listP);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("accion",3, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // accion ::= accion_open BORRRAR_SITIO_WEB MAYOR action_bodyP accion_close 
            {
              Object RESULT =null;
		int listPleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int listPright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ArrayList<Parameter> listP = (ArrayList<Parameter>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            actions.deleteSite(listP);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("accion",3, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // accion ::= accion_open NUEVA_PAGINA MAYOR action_bodyPE accion_close 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ActionPE a = (ActionPE)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            actions.createPage(a);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("accion",3, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // accion ::= accion_open BORRAR_PAGINA MAYOR action_bodyP accion_close 
            {
              Object RESULT =null;
		int listPleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int listPright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ArrayList<Parameter> listP = (ArrayList<Parameter>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            actions.deletePage(listP);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("accion",3, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // accion ::= accion_open MODIFICAR_PAGINA MAYOR action_bodyPE accion_close 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ActionPE a = (ActionPE)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            actions.editPage(a);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("accion",3, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // accion ::= accion_open AGREGAR_COMPONENTE MAYOR action_bodyPA accion_close 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ActionPA a = (ActionPA)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            actions.createComponent(a);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("accion",3, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // accion ::= accion_open BORRAR_COMPONENTE MAYOR action_bodyPA accion_close 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ActionPA a = (ActionPA)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            actions.deleteComponent(a);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("accion",3, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // accion ::= accion_open MODIFICAR_COMPONENTE MAYOR action_bodyPA accion_close 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ActionPA a = (ActionPA)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            actions.editComponent(a);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("accion",3, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // accion_open ::= MENOR ACCION NOMBRE EQUAL 
            {
              Object RESULT =null;

              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("accion_open",4, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-3)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // accion_close ::= MENOR SLASH ACCION MAYOR 
            {
              Object RESULT =null;

              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("accion_close",5, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-3)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // action_bodyP ::= parameters 
            {
              ArrayList<Parameter> RESULT =null;
		int listPleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int listPright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		ArrayList<Parameter> listP = (ArrayList<Parameter>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		
                RESULT = listP;
                
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("action_bodyP",15, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // action_bodyPE ::= parameters etiquetas 
            {
              ActionPE RESULT =null;
		int listPleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int listPright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ArrayList<Parameter> listP = (ArrayList<Parameter>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		int listEleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int listEright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		ArrayList<Label> listE = (ArrayList<Label>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		
                RESULT = new ActionPE(listP, listE);
                
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("action_bodyPE",11, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // action_bodyPE ::= etiquetas parameters 
            {
              ActionPE RESULT =null;
		int listEleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int listEright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ArrayList<Label> listE = (ArrayList<Label>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		int listPleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int listPright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		ArrayList<Parameter> listP = (ArrayList<Parameter>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		
                RESULT = new ActionPE(listP, listE);
                
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("action_bodyPE",11, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // action_bodyPA ::= parameters atributos 
            {
              ActionPA RESULT =null;
		int listPleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int listPright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ArrayList<Parameter> listP = (ArrayList<Parameter>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		int listAleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int listAright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		ArrayList<Attribute> listA = (ArrayList<Attribute>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		
              RESULT = new ActionPA(listP, listA);
              
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("action_bodyPA",10, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // action_bodyPA ::= atributos parameters 
            {
              ActionPA RESULT =null;
		int listAleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int listAright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ArrayList<Attribute> listA = (ArrayList<Attribute>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		int listPleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int listPright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		ArrayList<Parameter> listP = (ArrayList<Parameter>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		
              RESULT = new ActionPA(listP, listA);
              
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("action_bodyPA",10, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // parameters ::= MENOR PARAMETROS MAYOR parametrosP MENOR SLASH PARAMETROS MAYOR 
            {
              ArrayList<Parameter> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)).right;
		ArrayList<Parameter> list = (ArrayList<Parameter>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)).value;
		
            RESULT = list;
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parameters",13, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-7)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // parametrosP ::= parameter_p 
            {
              ArrayList<Parameter> RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Parameter p = (Parameter)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		
            ArrayList<Parameter> a = new ArrayList<>();
            a.add(p);
            RESULT = a;
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parametrosP",14, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // parametrosP ::= parametrosP parameter_p 
            {
              ArrayList<Parameter> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ArrayList<Parameter> a = (ArrayList<Parameter>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Parameter p = (Parameter)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		
            a.add(p);
            RESULT = a;
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parametrosP",14, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // parameter_p ::= parameter_open ID MAYOR PARAM parameter_close 
            {
              Parameter RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Parameter("ID",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parameter_p",12, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // parameter_p ::= parameter_open USUARIO_CREACION MAYOR PARAM parameter_close 
            {
              Parameter RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Parameter("USUARIO_CREACION",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parameter_p",12, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // parameter_p ::= parameter_open FECHA_CREACION MAYOR PARAM parameter_close 
            {
              Parameter RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Parameter("FECHA_CREACION",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parameter_p",12, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // parameter_p ::= parameter_open FECHA_MODIFICACION MAYOR PARAM parameter_close 
            {
              Parameter RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Parameter("FECHA_MODIFICACION",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parameter_p",12, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // parameter_p ::= parameter_open USUARIO_MODIFICACION MAYOR PARAM parameter_close 
            {
              Parameter RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Parameter("USUARIO_MODIFICACION",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parameter_p",12, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // parameter_p ::= parameter_open TITULO MAYOR PARAM parameter_close 
            {
              Parameter RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Parameter("TITULO",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parameter_p",12, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // parameter_p ::= parameter_open SITIO MAYOR PARAM parameter_close 
            {
              Parameter RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Parameter("SITIO",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parameter_p",12, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // parameter_p ::= parameter_open PADRE MAYOR PARAM parameter_close 
            {
              Parameter RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Parameter("PADRE",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parameter_p",12, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // parameter_p ::= parameter_open PAGINA MAYOR PARAM parameter_close 
            {
              Parameter RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Parameter("PAGINA",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parameter_p",12, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // parameter_p ::= parameter_open CLASE MAYOR PARAM parameter_close 
            {
              Parameter RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Parameter("CLASE",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parameter_p",12, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // parameter_open ::= MENOR PARAMETRO NOMBRE EQUAL 
            {
              Object RESULT =null;

              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parameter_open",6, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-3)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // parameter_close ::= MENOR SLASH PARAMETRO MAYOR 
            {
              Object RESULT =null;

              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("parameter_close",7, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-3)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // etiquetas ::= MENOR ETIQUETAS MAYOR etiquetaP MENOR SLASH ETIQUETAS MAYOR 
            {
              ArrayList<Label> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)).right;
		ArrayList<Label> list = (ArrayList<Label>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)).value;
		
            RESULT = list;
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("etiquetas",17, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-7)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // etiquetaP ::= etiqueta 
            {
              ArrayList<Label> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Label e = (Label)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		
             ArrayList<Label> a = new ArrayList<>();
             a.add(e);
             RESULT = a;
             
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("etiquetaP",18, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // etiquetaP ::= etiquetaP etiqueta 
            {
              ArrayList<Label> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ArrayList<Label> a = (ArrayList<Label>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Label e = (Label)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		
             a.add(e);
             RESULT = a;
             
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("etiquetaP",18, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // etiqueta ::= MENOR ETIQUETA VALOR EQUAL CADENA SLASH MAYOR 
            {
              Label RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-2)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-2)).value;
		
            RESULT = new Label(c, cleft, cright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("etiqueta",16, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-6)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // atributos ::= MENOR ATRIBUTOS MAYOR atributoP MENOR SLASH ATRIBUTOS MAYOR 
            {
              ArrayList<Attribute> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)).right;
		ArrayList<Attribute> list = (ArrayList<Attribute>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)).value;
		
            RESULT = list;
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("atributos",20, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-7)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // atributoP ::= attributes_p 
            {
              ArrayList<Attribute> RESULT =null;
		int attleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int attright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Attribute att = (Attribute)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		
             ArrayList<Attribute> a = new ArrayList<>();
             a.add(att);
             RESULT = a;
             
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("atributoP",21, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // atributoP ::= atributoP attributes_p 
            {
              ArrayList<Attribute> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		ArrayList<Attribute> a = (ArrayList<Attribute>)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		int attleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).left;
		int attright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()).right;
		Attribute att = (Attribute)((java_cup.runtime.Symbol) CUP$XMLParser$stack.peek()).value;
		
            a.add(att);
            RESULT = a;
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("atributoP",21, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // attributes_p ::= atributo_open TEXTO MAYOR PARAM atributo_close 
            {
              Attribute RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Attribute("TEXTO",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("attributes_p",19, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // attributes_p ::= atributo_open ALINEACION MAYOR PARAM atributo_close 
            {
              Attribute RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Attribute("ALINEACION",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("attributes_p",19, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // attributes_p ::= atributo_open COLOR MAYOR PARAM atributo_close 
            {
              Attribute RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Attribute("COLOR",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("attributes_p",19, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // attributes_p ::= atributo_open ORIGEN MAYOR PARAM atributo_close 
            {
              Attribute RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Attribute("ORIGEN",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("attributes_p",19, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // attributes_p ::= atributo_open ALTURA MAYOR PARAM atributo_close 
            {
              Attribute RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Attribute("ALTURA",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("attributes_p",19, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // attributes_p ::= atributo_open ANCHO MAYOR PARAM atributo_close 
            {
              Attribute RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Attribute("ANCHO",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("attributes_p",19, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // attributes_p ::= atributo_open PADRE MAYOR PARAM atributo_close 
            {
              Attribute RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Attribute("PADRE",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("attributes_p",19, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // attributes_p ::= atributo_open ETIQUETAS_NOMBRE MAYOR PARAM atributo_close 
            {
              Attribute RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-1)).value;
		
            RESULT = new Attribute("ETIQUETAS",p, pleft, pright);
            
              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("attributes_p",19, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-4)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // atributo_open ::= MENOR ATRIBUTO NOMBRE EQUAL 
            {
              Object RESULT =null;

              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("atributo_open",8, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-3)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // atributo_close ::= MENOR SLASH ATRIBUTO MAYOR 
            {
              Object RESULT =null;

              CUP$XMLParser$result = parser.getSymbolFactory().newSymbol("atributo_close",9, ((java_cup.runtime.Symbol)CUP$XMLParser$stack.elementAt(CUP$XMLParser$top-3)), ((java_cup.runtime.Symbol)CUP$XMLParser$stack.peek()), RESULT);
            }
          return CUP$XMLParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$XMLParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$XMLParser$do_action(
    int                        CUP$XMLParser$act_num,
    java_cup.runtime.lr_parser CUP$XMLParser$parser,
    java.util.Stack            CUP$XMLParser$stack,
    int                        CUP$XMLParser$top)
    throws java.lang.Exception
    {
              return CUP$XMLParser$do_action_part00000000(
                               CUP$XMLParser$act_num,
                               CUP$XMLParser$parser,
                               CUP$XMLParser$stack,
                               CUP$XMLParser$top);
    }
}

}
